source "https://rubygems.org"

group :development, :test do
  gem 'factory_girl_rails', '~> 4.5'
  gem 'rspec-rails', '~> 3.3'
  gem 'pry-byebug', '~> 3.1'
  gem 'pry-rails', '~> 0.3'
  gem 'spring', '~> 1.3'
  gem 'web-console', '~> 2.2'
  gem 'vcr', '~> 2.9.3'
  gem 'webmock', '~> 1.21.0'
end

group :development do
  gem 'guard-rspec', '~> 4.6'
  gem 'spring-commands-rspec', '~> 1.0'
end

group :test do
  gem 'capybara', '~> 2.4'
  gem 'database_cleaner', '~> 1.4'
  gem 'faker', '~> 1.4'
  gem 'launchy', '~> 2.4'
  gem 'poltergeist', '~> 1.6'
  gem 'selenium-webdriver', '~> 2.46'
  gem 'simplecov', '~> 0.10', {:require=>false}
end

group :production do
  gem 'rails_12factor', '~> 0.0'
end


gem 'rails', '~> 4.2'
gem 'pg', '~> 0.18'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '~> 2.7'
gem 'coffee-rails', '~> 4.1'
gem 'jquery-rails', '~> 4.0'
gem 'turbolinks', '~> 2.5'
gem 'jbuilder', '~> 2.3'
gem 'sdoc', '~> 0.4', {:group=>:doc}
gem 'active_model_serializers', '~> 0.9'
gem 'unicorn', '~> 4.9'
gem 'ipaddress', '~> 0.8'
gem 'faraday', '~> 0.9'
gem 'faraday_middleware', '~> 0.10'
gem 'pessimize', '~> 0.1'


